baseURL = "https://613covid.ca"
languageCode = "en-us"
title = "Ottawa COVID19"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "./docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Visualizations"
    url = ""
    weight = 2

[[menu.main]]
    name = "Peak hospitalization projections"
    url = "/#peak-hosp-projections"
    parent = "Visualizations"
    weight = 1
    
[[menu.main]]
    name = "Acute Care Projections"
    url = "/#acute-care-projections"
    parent = "Visualizations"
    weight = 2

[[menu.main]]
    name = "ICU Projections"
    url = "/#icu-projections"
    parent = "Visualizations"
    weight = 3

[[menu.main]]
    name = "Ventilator Projections"
    url = "/#ventilator-projections"
    parent = "Visualizations"
    weight = 4
    
[[menu.main]]
    name = "Physical distancing"
    url = "/more/#distancing"
    parent = "Visualizations"
    weight = 5

[[menu.main]]
    name = "Flattening the curve"
    url = "/more/#flatten-curve"
    parent = "Visualizations"
    weight = 6

[[menu.main]]
    name = "Mortality Projections"
    url = "/#deaths"
    parent = "Visualizations"
    weight = 5

[[menu.main]]
    name = "Model"
    url = "/model/"
    weight = 3

[[menu.main]]
    name = "More"
    url = "/more/"
    weight = 4
    
[[menu.main]]
    name = "Model use"
    url = "/more/#use"
    parent = "More"
    weight = 1

[[menu.main]]
    name = "Model accuracy"
    url = "/more/#accuracy"
    parent = "More"
    weight = 2   
    
[[menu.main]]
    name = "Scenarios of physical disrtancing"
    url = "/more/#scenarios"
    parent = "More"
    weight = 3  
    
[[menu.main]]
    name = "Physical distancing"
    url = "/more/#distancing"
    parent = "More"
    weight = 4 
    
[[menu.main]]
    name = "Physical distancing effectiveness"
    url = "/more/#distancing-effectiveness"
    parent = "More"
    weight = 5 
    
[[menu.main]]
    name = "Flatten the curve"
    url = "/more/#flatten-curve"
    parent = "More"
    weight = 6  

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[[menu.main]]
    name = "Changelog"
    url = "/change-log/"
    weight = 6

[params]
    description = "Ottawa COVID-19 hospital projections."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.png"