baseURL = "https://613covid.ca"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Ottawa COVID19"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "./docs"

[languages]
  [languages.en]
    contentDir = "./content/en"
    languageName = "English"
    weight = 1
  [languages.fr]
    contentDir = "./content/fr"
    languageName = "French"
    weight = 2


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Visualizations"
    url = ""
    weight = 2
    
[[menu.main]]
    name = "Observed cases"
    url = "/#observed-cases"
    parent = "viz"
    weight = 1

[[menu.main]]
    name = "Observed hospital census"
    url = "/#observed-census"
    parent = "viz"
    weight = 2
    
[[menu.main]]
    name = "Observed daily hospital admissions"
    url = "/#observed-admits"
    parent = "viz"
    weight = 3
    
[[menu.main]]
    name = "Case projections"
    url = "/#case-projections"
    parent = "viz"
    weight = 4
    
[[menu.main]]
    name = "Hospitalization projections"
    url = "/#hospitalization-projections"
    parent = "viz"
    weight = 5
    
[[menu.main]]
    name = "Model"
    url = "/model/"
    weight = 3
    
[[menu.main]]
    name = "Model parameters"
    url = "/model/"
    parent = "model"
    weight = 1
    
[[menu.main]]
    name = "Hospital data"
    url = "/model/#hospital-census"
    parent = "model"
    weight = 2

[[menu.main]]
    name = "Physical distancing"
    url = "/model/#physical-distancing"
    parent = "model"
    weight = 3

[[menu.main]]
    name = "Physical distancing"
    url = "/model/#distancing-math"
    parent = "model"
    weight = 4
    
[[menu.main]]
    name = "Physical distancing"
    url = "/model/#distancing"
    parent = "model"
    weight = 5
    
[[menu.main]]
    name = "Input parameters"
    url = "/model/#parameters"
    parent = "model"
    weight = 6

[[menu.main]]
    name = "Input parameters"
    url = "/model/#plot-data"
    parent = "model"
    weight = 7
    
[[menu.main]]
    name = "References"
    url = "/model/#references"
    parent = "model"
    weight = 8

[[menu.main]]
    name = "more"
    url = "/more/"
    weight = 4
    
[[menu.main]]
    name = "Model use"
    url = "/more/#use"
    parent = "more"
    weight = 1

[[menu.main]]
    name = "Model accuracy"
    url = "/more/#accuracy"
    parent = "more"
    weight = 2   
    
[[menu.main]]
    name = "Scenarios of physical distancing"
    url = "/more/#scenarios"
    parent = "more"
    weight = 3  
    
[[menu.main]]
    name = "Physical distancing"
    url = "/more/#distancing"
    parent = "more"
    weight = 4 
    
[[menu.main]]
    name = "Physical distancing effectiveness"
    url = "/more/#distancing-effectiveness"
    parent = "more"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[[menu.main]]
    name = "Changelog"
    url = "/change-log/"
    weight = 6

[params]
    description = "Ottawa COVID-19 hospital projections."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.png"