# This is a workflow to automate the dataset creation for 613covid.ca

name: Dataset-creation

# Runs everyday at 12:30pm EST/EDT (4:30pm UTC)
on: 
  push:
    branches: master
jobs:
  dataset-creation:
    runs-on: "ubuntu-latest"
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.ACTION_TOKEN }}
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - name: Install renv package
        run: R -e 'install.packages("renv")'
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Install dependencies
        run: R -e 'renv::restore()'
      - name: Prepare data
        run: Rscript R/dataset_creation.R
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          BRANCH_NAME: 'master' #optional defaults to master
