# This is a workflow to automate the dataset creation for 613covid.ca and 
# run short-term hospitalization projections

name: Dataset-creation

# Runs everyday at 12:30pm EST/EDT (5:30pm UTC)
on:
  schedule:
    - cron: '30 16 * * *'
jobs:
  dataset-creation:
    runs-on: "ubuntu-latest"
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.ACTION_TOKEN }}
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Install libnode-dev
        run: |
          sudo add-apt-repository ppa:cran/v8
          sudo apt-get update
          sudo apt-get install libnode-dev
      - name: Install snap version of nodejs
        run: sudo snap install node --classic --channel=14
      - name: Install V8
        run: Rscript -e 'install.packages("V8")'
      - name: Install renv package
        run: R -e 'install.packages("renv")'
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Install dependencies
        run: R -e 'renv::restore()'
      - name: Prepare data
        run: Rscript R/dataset_creation.R
      - name: Run short term projections 
        run: Rscript R/short_term_projections.R
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          BRANCH_NAME: 'master' #optional defaults to master
      - name: Merge master -> hosp-projections
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: hosp-projections
          github_token: ${{ secrets.ACTION_TOKEN }} 
