# This workflow generates hospital projections using the CHIME bayesian simulation from Open Ottawa hospitalization data

name: Hospital-projections

on: push

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown", "knitr", "tidyverse", "jsonlite", "dplyr", "reticulate"))'
      - name: Run projections
        run: Rscript -e 'rmarkdown::render_site("hosp-projections.Rmd")'
