# This workflow generates hospital projections using the CHIME bayesian simulation from Open Ottawa hospitalization data

name: Hospital-projections

on: push

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: r-lib/actions/setup-r@v1
      - uses: Actions-R-Us/default-env@v1
        env:
          GITHUB_ACTOR: 'github'
          GITHUB_REF: 'dev'
      - name: Install packages
        run: Rscript -e 'install.packages(c("tidyverse", "jsonlite"))'
      - name: Load tidyverse
        run: Rscript -e 'library(tidyverse)'
      - name: Source open Ottawa functions
        run: Rscript -e 'source("R/open_ottawa_scripts.R")' 
      - name: Source CHIME processing functions
        run: Rscript -e 'source("R/chime_functions.R")'
      - name: Print environment
        run: Rscript -e 'lapply(ls(),function(x)get(x))'
