# This workflow generates hospital projections using the CHIME bayesian simulation from Open Ottawa hospitalization data.

name: Hospital-projections

# Runs every Tuesday & Friday at 12:00pm EST/EDT (1pm UTC)
on: 
  schedule:
    - cron: '0 16 * * 2,5'
  workflow_dispatch:

jobs:
  data-prep:
    runs-on: "macOS-latest"
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
        with:
          ref: hosp-projections
          token: ${{ secrets.ACTION_TOKEN }}
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - name: Install V8
        run: Rscript -e 'install.packages("V8")'
      - name: Install renv package
        run: R -e 'install.packages("renv")'
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install dependencies
        run: R -e 'renv::restore()'
      - name: Prepare data
        run: Rscript R/chime_dataprep.R
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: 'hosp-projections'
  simulation:
    runs-on: "macOS-latest"
    needs: data-prep
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: hosp-projections
          token: ${{ secrets.ACTION_TOKEN }}
      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: "3.8"
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install python dependencies 
        shell: pwsh
        run: pip install -r Python/requirements.txt
      - name: Run CHIME simulation
        shell: pwsh
        run: python Python/_01_GOF_sims.py -p Python/data/OTT_parameters.csv -t Python/data/OTT_ts.csv  --reopen_day 14 --reopen_caps 1 1.1 0.9 --save_reopening_csv --one_reopen --reopen_from_today
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: 'hosp-projections'
  postsim:
    runs-on: "macOS-latest"
    needs: simulation
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
        with:
          ref: hosp-projections
          token: ${{ secrets.ACTION_TOKEN }}
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - name: Install V8
        run: Rscript -e 'install.packages("V8")'
      - name: Install renv package
        run: R -e 'install.packages("renv")'
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install dependencies
        run: R -e 'renv::restore()'
      - name: Prepare data
        run: Rscript R/chime_postsim.R
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: 'hosp-projections'
      - name: Push branch to master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: hosp-projections
          target_branch: master
          github_token: ${{ secrets.ACTION_TOKEN }} 
