# This workflow generates hospital projections using the CHIME bayesian simulation from Open Ottawa hospitalization data

name: Hospital-projections

on: push

jobs:
  data-prep:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("tidyverse", "jsonlite", "dplyr"))'
      - name: Source functions & export data to Python folder
        run: |
          Rscript -e 'source("R/open_ottawa_scripts.R")'
          Rscript -e 'source("R/chime_functions.R")'
          Rscript -e 'hosp_export(json_address = "https://opendata.arcgis.com/datasets/6bfe7832017546e5b30c5cc6a201091b_0/FeatureServer/0/query?where=1%3D1&outFields=_Date,Cases_Currently_in_Hospital&outSR=4326&f=json", starting_date = "2020-07-07", dest = "Python/data/OTT_ts.csv")'
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'dev' #optional defaults to master
  simulation:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: "3.8"
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install python dependencies 
        shell: pwsh
        run: pip install -r Python/requirements.txt
      - name: Run CHIME simulation
        shell: pwsh
        run: python Python/_01_GOF_sims.py -p Python/data/OTT_parameters.csv -t Python/data/OTT_ts.csv  --reopen_day 14 --reopen_caps 1 1.1 0.9 --save_reopening_csv --one_reopen --reopen_from_today
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'dev' #optional defaults to master
