# This workflow generates hospital projections using the CHIME bayesian simulation from Open Ottawa hospitalization data

name: Hospital-projections

# Runs every Tuesday at 12:00pm EST/EDT (1pm UTC) or push
on: 
  schedule:
    - cron: '0 16 * * 2'
  push:
    branches: dev

jobs:
  data-prep:
    runs-on: "ubuntu-latest"
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.3'
      - name: Install renv package
        run: R -e 'install.packages("renv")'
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Install dependencies
        run: R -e 'renv::restore()'
      - name: Prepare data
        run: Rscript R/chime_dataprep.R
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'dev' #optional defaults to master
  simulation:
    runs-on: "ubuntu-latest"
    needs: data-prep
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: "3.8"
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install python dependencies 
        shell: pwsh
        run: pip install -r Python/requirements.txt
      - name: Run CHIME simulation
        shell: pwsh
        run: python Python/_01_GOF_sims.py -p Python/data/OTT_parameters.csv -t Python/data/OTT_ts.csv  --reopen_day 14 --reopen_caps 1 1.1 0.9 --save_reopening_csv --one_reopen --reopen_from_today
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'dev' #optional defaults to master
