# This is a workflow to automate the deployment of 613covid.ca

name: Website-update

# Runs everyday at 1:30pm EST/EDT (5:30pm UTC)
on: 
  schedule:
    - cron: '30 17 * * *'
  push:
    branches: master

jobs:
  dataset-creation:
    runs-on: "ubuntu-latest"
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - name: Install renv package
        run: R -e 'install.packages("renv")'
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev
      - name: Install dependencies
        run: R -e 'renv::restore()'
      - name: Prepare data
        run: Rscript R/dataset_creation.R
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master' #optional defaults to master
  blogdown:
    name: Render-Blog
    needs: dataset-creation
    runs-on: "macOS-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.3'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install V8
        run: Rscript -e 'install.packages("V8")'
      - name: Install rmarkdown and blogdown
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown", "knitr"))'
      - name: Install rmd packages
        run: Rscript -e 'install.packages(c("plotly", "tidyverse", "jsonlite", "ggplot2", "dplyr", "tidyr", "lubridate", "stats", "remotes", "zoo", "stringr"))'
      - name: Install RStan
        run: Rscript -e 'install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)'
      - name: Install covidseir
        run: Rscript -e 'remotes::install_github("seananderson/covidseir")'
      - name: install hugo
        run: Rscript -e 'blogdown::install_hugo()'
      - name: Render website
        run: Rscript -e 'blogdown::build_site(build_rmd = TRUE)'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
